/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Cars;

import GUI.Cancel.Cancel;
import GUI.Customers.DisplayCustomer;
import GUI.RentingCar.RentingInformation;
import classes.Car;
import classes.SystemClass;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author ereno
 */
public class DisplayCar extends javax.swing.JFrame {

    /**
     * Creates new form DisplayCar
     */
    public DisplayCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonRentCar = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonCustomers = new javax.swing.JButton();
        jButtonCars = new javax.swing.JButton();
        jPanelImportant = new javax.swing.JPanel();
        jLabelImportant = new javax.swing.JLabel();
        jButtonAddNewCar = new javax.swing.JButton();
        jLabelCars = new javax.swing.JLabel();
        jPanelCars = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jComboBoxSearch = new javax.swing.JComboBox<>();
        jLabelCarID = new javax.swing.JLabel();
        jTextFieldCarID = new javax.swing.JTextField();
        jLabelBrand = new javax.swing.JLabel();
        jTextFieldBrand = new javax.swing.JTextField();
        jLabelModel = new javax.swing.JLabel();
        jTextFieldModel = new javax.swing.JTextField();
        jLabelFuelType = new javax.swing.JLabel();
        jTextFieldFuelType = new javax.swing.JTextField();
        jLabelGearType = new javax.swing.JLabel();
        jTextFieldGearType = new javax.swing.JTextField();
        jLabelCarType = new javax.swing.JLabel();
        jLabelModelYear = new javax.swing.JLabel();
        jTextFieldModelYear = new javax.swing.JTextField();
        jLabelPrice = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jComboBoxCarType = new javax.swing.JComboBox<>();
        jButtonUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonRentCar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRentCar.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButtonRentCar.setText("Rent a Car");
        jButtonRentCar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jButtonRentCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRentCarActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButtonCancel.setText("Cancel the Reservation");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonCustomers.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCustomers.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButtonCustomers.setText("Customers");
        jButtonCustomers.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButtonCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomersActionPerformed(evt);
            }
        });

        jButtonCars.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCars.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButtonCars.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCars.setText("Cars");
        jButtonCars.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanelImportant.setBackground(new java.awt.Color(0, 0, 0));

        jLabelImportant.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jLabelImportant.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImportant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImportant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/alert.png"))); // NOI18N
        jLabelImportant.setText("IMPORTANT NOTE: During the COVID-19 pandemic, our all cars have been sterilized for your health.");

        javax.swing.GroupLayout jPanelImportantLayout = new javax.swing.GroupLayout(jPanelImportant);
        jPanelImportant.setLayout(jPanelImportantLayout);
        jPanelImportantLayout.setHorizontalGroup(
            jPanelImportantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImportant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelImportantLayout.setVerticalGroup(
            jPanelImportantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImportant, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jButtonAddNewCar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAddNewCar.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButtonAddNewCar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddNewCar.setText("Add New Car");
        jButtonAddNewCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewCarActionPerformed(evt);
            }
        });

        jLabelCars.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        jLabelCars.setText("Cars");

        jPanelCars.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCars.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabelSearch.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jLabelSearch.setText("Search by Brand, Model and Year:");

        jComboBoxSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxSearch.setBorder(null);
        jComboBoxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSearchActionPerformed(evt);
            }
        });

        jLabelCarID.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabelCarID.setText("Car ID");

        Border border = BorderFactory.createLineBorder(Color.BLACK, 1, true);
        jTextFieldCarID.setBorder(BorderFactory.createCompoundBorder(border,
            BorderFactory.createEmptyBorder(0, 10, 0, 0)));

    jLabelBrand.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelBrand.setText("Brand");

    jTextFieldBrand.setBorder(BorderFactory.createCompoundBorder(border,
        BorderFactory.createEmptyBorder(0, 10, 0, 0)));

jLabelModel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
jLabelModel.setText("Model");

jTextFieldModel.setBorder(BorderFactory.createCompoundBorder(border,
    BorderFactory.createEmptyBorder(0, 10, 0, 0)));

    jLabelFuelType.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelFuelType.setText("Fuel Type");

    jTextFieldFuelType.setBorder(BorderFactory.createCompoundBorder(border,
        BorderFactory.createEmptyBorder(0, 10, 0, 0)));

jLabelGearType.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
jLabelGearType.setText("Gear Type");

jTextFieldGearType.setBorder(BorderFactory.createCompoundBorder(border,
    BorderFactory.createEmptyBorder(0, 10, 0, 0)));

    jLabelCarType.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelCarType.setText("Car Type");

    jLabelModelYear.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelModelYear.setText("Model Year");

    jTextFieldModelYear.setBorder(BorderFactory.createCompoundBorder(border,
        BorderFactory.createEmptyBorder(0, 10, 0, 0)));

jLabelPrice.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
jLabelPrice.setText("Price");

jTextFieldPrice.setBorder(BorderFactory.createCompoundBorder(border,
    BorderFactory.createEmptyBorder(0, 10, 0, 0)));
    jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldPriceActionPerformed(evt);
        }
    });

    jButtonEdit.setBackground(new java.awt.Color(0, 0, 0));
    jButtonEdit.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
    jButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
    jButtonEdit.setText("EDIT CAR");
    jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditActionPerformed(evt);
        }
    });

    jButtonSave.setBackground(new java.awt.Color(0, 0, 0));
    jButtonSave.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
    jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
    jButtonSave.setText("SAVE CAR");
    jButtonSave.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonSaveActionPerformed(evt);
        }
    });

    jComboBoxCarType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economic", "Comfort", "Luxury" }));
    jComboBoxCarType.setSelectedIndex(-1);

    javax.swing.GroupLayout jPanelCarsLayout = new javax.swing.GroupLayout(jPanelCars);
    jPanelCars.setLayout(jPanelCarsLayout);
    jPanelCarsLayout.setHorizontalGroup(
        jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelCarsLayout.createSequentialGroup()
            .addGap(115, 115, 115)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCarsLayout.createSequentialGroup()
                    .addComponent(jLabelSearch)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBoxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelCarsLayout.createSequentialGroup()
                    .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelGearType)
                        .addComponent(jTextFieldGearType, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(110, 110, 110)
                    .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelCarType)
                        .addComponent(jComboBoxCarType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelCarsLayout.createSequentialGroup()
                    .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelModelYear)
                        .addComponent(jTextFieldModelYear, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(110, 110, 110)
                    .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPrice)))
                .addGroup(jPanelCarsLayout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelCarsLayout.createSequentialGroup()
                    .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelCarID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelModel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldCarID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(jTextFieldModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                    .addGap(110, 110, 110)
                    .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFuelType)
                        .addComponent(jLabelBrand))))
            .addContainerGap(116, Short.MAX_VALUE))
    );
    jPanelCarsLayout.setVerticalGroup(
        jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelCarsLayout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBoxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelCarID)
                .addComponent(jLabelBrand))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldCarID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelModel)
                .addComponent(jLabelFuelType))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelGearType)
                .addComponent(jLabelCarType))
            .addGap(5, 5, 5)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldGearType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBoxCarType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelModelYear)
                .addComponent(jLabelPrice))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldModelYear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(27, 27, 27)
            .addGroup(jPanelCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
            .addGap(27, 27, 27))
    );

    jTextFieldCarID.setEnabled(false);
    jTextFieldBrand.setEnabled(false);
    jTextFieldModel.setEnabled(false);
    jTextFieldFuelType.setEnabled(false);
    jTextFieldGearType.setEnabled(false);
    jTextFieldModelYear.setEnabled(false);
    jTextFieldPrice.setEnabled(false);
    jButtonSave.setEnabled(false);
    jComboBoxCarType.setEnabled(false);

    jButtonUpdate.setBackground(new java.awt.Color(0, 0, 0));
    jButtonUpdate.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
    jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
    jButtonUpdate.setText("UPDATE");
    jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonUpdateActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanelImportant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(jButtonRentCar)
            .addGap(29, 29, 29)
            .addComponent(jButtonCancel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonCustomers)
            .addGap(30, 30, 30)
            .addComponent(jButtonCars)
            .addGap(36, 36, 36))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(173, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabelCars)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButtonAddNewCar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanelCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(102, 102, 102))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanelImportant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonCars)
                .addComponent(jButtonCustomers)
                .addComponent(jButtonCancel)
                .addComponent(jButtonRentCar))
            .addGap(31, 31, 31)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddNewCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanelCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(27, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jButtonCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomersActionPerformed
        DisplayCustomer displayCustomer = new DisplayCustomer();
        displayCustomer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCustomersActionPerformed

    private void jButtonRentCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRentCarActionPerformed
        RentingInformation RentingInformation = new RentingInformation();
        RentingInformation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRentCarActionPerformed

    private void jButtonAddNewCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewCarActionPerformed
        AddCar addCar = new AddCar();
        addCar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAddNewCarActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        jComboBoxSearch.removeAllItems();
        for (Car car : SystemClass.cars) {
            jComboBoxSearch.insertItemAt(car.getBrand() + " " + car.getModel() + " (" + car.getModelYear() + ")", 0);
        }
        
        jTextFieldCarID.setText("");
        jTextFieldBrand.setText("");
        jTextFieldModel.setText("");
        jTextFieldFuelType.setText("");
        jTextFieldGearType.setText("");
        jComboBoxCarType.setSelectedIndex(-1);
        jTextFieldModelYear.setText("");
        jTextFieldPrice.setText("");
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jComboBoxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSearchActionPerformed
        System.out.println(jComboBoxSearch.getSelectedItem());
        
        int position = SystemClass.searchCarByBrand(jComboBoxSearch);
        
        jTextFieldCarID.setText(String.valueOf(SystemClass.cars.get(position).getCarID()));
        jTextFieldBrand.setText(SystemClass.cars.get(position).getBrand());
        jTextFieldModel.setText(SystemClass.cars.get(position).getModel());
        jTextFieldFuelType.setText(SystemClass.cars.get(position).getFuelType());
        jTextFieldGearType.setText(SystemClass.cars.get(position).getFuelType());
        jComboBoxCarType.setSelectedItem(SystemClass.cars.get(position).getCarType());
        jTextFieldModelYear.setText(String.valueOf(SystemClass.cars.get(position).getModelYear()));
        jTextFieldPrice.setText(String.valueOf(SystemClass.cars.get(position).getPrice()));
    }//GEN-LAST:event_jComboBoxSearchActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        jTextFieldBrand.setEnabled(true);
        jTextFieldModel.setEnabled(true);
        jTextFieldFuelType.setEnabled(true);
        jTextFieldGearType.setEnabled(true);
        jComboBoxCarType.setEnabled(true);
        jTextFieldModelYear.setEnabled(true);
        jTextFieldPrice.setEnabled(true);
        jButtonSave.setEnabled(true);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        int position = SystemClass.searchCarByBrand(jComboBoxSearch);
        
        // VİRGÜLLE YAZILAN FİYAT İÇİN TRY-CATCH YAZILACAK
        
        SystemClass.cars.get(position).setBrand(jTextFieldBrand.getText());
        SystemClass.cars.get(position).setModel(jTextFieldModel.getText());
        SystemClass.cars.get(position).setFuelType(jTextFieldFuelType.getText());
        SystemClass.cars.get(position).setGearType(jTextFieldGearType.getText());
        SystemClass.cars.get(position).setCarType((String) jComboBoxCarType.getSelectedItem());
        SystemClass.cars.get(position).setModelYear(Integer.parseInt(jTextFieldModelYear.getText()));
        SystemClass.cars.get(position).setPrice(Double.parseDouble(jTextFieldPrice.getText()));
        
        jTextFieldBrand.setEnabled(false);
        jTextFieldModel.setEnabled(false);
        jTextFieldFuelType.setEnabled(false);
        jTextFieldGearType.setEnabled(false);
        jComboBoxCarType.setEnabled(false);
        jTextFieldModelYear.setEnabled(false);
        jTextFieldPrice.setEnabled(false);
        jButtonSave.setEnabled(false);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        Cancel cancel = new Cancel();
        cancel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNewCar;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCars;
    private javax.swing.JButton jButtonCustomers;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonRentCar;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxCarType;
    private javax.swing.JComboBox<String> jComboBoxSearch;
    private javax.swing.JLabel jLabelBrand;
    private javax.swing.JLabel jLabelCarID;
    private javax.swing.JLabel jLabelCarType;
    private javax.swing.JLabel jLabelCars;
    private javax.swing.JLabel jLabelFuelType;
    private javax.swing.JLabel jLabelGearType;
    private javax.swing.JLabel jLabelImportant;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelModelYear;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCars;
    private javax.swing.JPanel jPanelImportant;
    private javax.swing.JTextField jTextFieldBrand;
    private javax.swing.JTextField jTextFieldCarID;
    private javax.swing.JTextField jTextFieldFuelType;
    private javax.swing.JTextField jTextFieldGearType;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldModelYear;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables
}
