/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.RentingCar;

import GUI.Cancel.Cancel;
import GUI.Cars.DisplayCar;
import GUI.Customers.DisplayCustomer;
import classes.Person;
import classes.SystemClass;

/**
 *
 * @author ereno
 */
public class RentingExtras extends javax.swing.JFrame {

    /**
     * Creates new form RentingExtras
     */
    public RentingExtras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonRentCar = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonCustomers = new javax.swing.JButton();
        jButtonCars = new javax.swing.JButton();
        jPanelImportant = new javax.swing.JPanel();
        jLabelImportant = new javax.swing.JLabel();
        jLabelRentCar = new javax.swing.JLabel();
        jPanelInformation = new javax.swing.JPanel();
        jScrollPaneInformation = new javax.swing.JScrollPane();
        jTextAreaInformation = new javax.swing.JTextArea();
        jPanelExtras = new javax.swing.JPanel();
        jLabelExtras = new javax.swing.JLabel();
        jLabelChildSeat = new javax.swing.JLabel();
        jCheckBoxChildSeat = new javax.swing.JCheckBox();
        jLabelNavigation = new javax.swing.JLabel();
        jCheckBoxNavigation = new javax.swing.JCheckBox();
        jLabelSnowTire = new javax.swing.JLabel();
        jCheckBoxSnowTire = new javax.swing.JCheckBox();
        jLabelHGS = new javax.swing.JLabel();
        jCheckBoxHGS = new javax.swing.JCheckBox();
        jLabeScooter = new javax.swing.JLabel();
        jCheckBoxScooter = new javax.swing.JCheckBox();
        jLabelProtection = new javax.swing.JLabel();
        jLabelTire = new javax.swing.JLabel();
        jCheckBoxTire = new javax.swing.JCheckBox();
        jLabelWindow = new javax.swing.JLabel();
        jCheckBoxWindow = new javax.swing.JCheckBox();
        jLabelHeadlight = new javax.swing.JLabel();
        jCheckBoxHeadlight = new javax.swing.JCheckBox();
        jLabelComprehensive = new javax.swing.JLabel();
        jCheckBoxComprehensive = new javax.swing.JCheckBox();
        jLabelTotalPrice = new javax.swing.JLabel();
        jTextFieldTotalPrice = new javax.swing.JTextField();
        jButtonRent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonRentCar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRentCar.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButtonRentCar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRentCar.setText("Rent a Car");
        jButtonRentCar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jButtonRentCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRentCarActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButtonCancel.setText("Cancel the Reservation");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonCustomers.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCustomers.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButtonCustomers.setText("Customers");
        jButtonCustomers.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButtonCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomersActionPerformed(evt);
            }
        });

        jButtonCars.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCars.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButtonCars.setText("Cars");
        jButtonCars.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButtonCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarsActionPerformed(evt);
            }
        });

        jPanelImportant.setBackground(new java.awt.Color(0, 0, 0));

        jLabelImportant.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jLabelImportant.setForeground(new java.awt.Color(255, 255, 255));
        jLabelImportant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImportant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/alert.png"))); // NOI18N
        jLabelImportant.setText("IMPORTANT NOTE: During the COVID-19 pandemic, our all cars have been sterilized for your health.");

        javax.swing.GroupLayout jPanelImportantLayout = new javax.swing.GroupLayout(jPanelImportant);
        jPanelImportant.setLayout(jPanelImportantLayout);
        jPanelImportantLayout.setHorizontalGroup(
            jPanelImportantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImportant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
        );
        jPanelImportantLayout.setVerticalGroup(
            jPanelImportantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImportant, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jLabelRentCar.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        jLabelRentCar.setText("Rent a Car");

        jTextAreaInformation.setColumns(20);
        jTextAreaInformation.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextAreaInformation.setRows(5);
        jTextAreaInformation.setText("PLEASE UPDATE THE PAGE.");
        jScrollPaneInformation.setViewportView(jTextAreaInformation);
        jTextAreaInformation.setEditable(false);

        javax.swing.GroupLayout jPanelInformationLayout = new javax.swing.GroupLayout(jPanelInformation);
        jPanelInformation.setLayout(jPanelInformationLayout);
        jPanelInformationLayout.setHorizontalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanelInformationLayout.setVerticalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        jPanelExtras.setBackground(new java.awt.Color(255, 255, 255));
        jPanelExtras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabelExtras.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabelExtras.setText("Recommended Extras");

        jLabelChildSeat.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabelChildSeat.setText("Child Seat          30TL/day");

        jCheckBoxChildSeat.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxChildSeat.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jCheckBoxChildSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxChildSeatActionPerformed(evt);
            }
        });

        jLabelNavigation.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabelNavigation.setText("Navigation         20TL/day");

        jCheckBoxNavigation.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxNavigation.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jCheckBoxNavigation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNavigationActionPerformed(evt);
            }
        });

        jLabelSnowTire.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabelSnowTire.setText("Snow Tire           50TL/day");

        jCheckBoxSnowTire.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxSnowTire.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jCheckBoxSnowTire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSnowTireActionPerformed(evt);
            }
        });

        jLabelHGS.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabelHGS.setText("HGS                    60TL/day");

        jCheckBoxHGS.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxHGS.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jCheckBoxHGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHGSActionPerformed(evt);
            }
        });

        jLabeScooter.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabeScooter.setText("Scooter               15TL/day");

        jCheckBoxScooter.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxScooter.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jCheckBoxScooter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxScooterActionPerformed(evt);
            }
        });

        jLabelProtection.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabelProtection.setText("Recommended Protection Options");

        jLabelTire.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabelTire.setText("Tire Protection              20TL/day");

        jCheckBoxTire.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxTire.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jCheckBoxTire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTireActionPerformed(evt);
            }
        });

        jLabelWindow.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabelWindow.setText("Window Protection      25TL/day");

        jCheckBoxWindow.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxWindow.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jCheckBoxWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWindowActionPerformed(evt);
            }
        });

        jLabelHeadlight.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabelHeadlight.setText("Headlight Protection    15TL/day");

        jCheckBoxHeadlight.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxHeadlight.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jCheckBoxHeadlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHeadlightActionPerformed(evt);
            }
        });

        jLabelComprehensive.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabelComprehensive.setText("Comprehensive             50TL/day");

        jCheckBoxComprehensive.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxComprehensive.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jCheckBoxComprehensive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxComprehensiveActionPerformed(evt);
            }
        });

        jLabelTotalPrice.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabelTotalPrice.setText("Total Price:");

        jTextFieldTotalPrice.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTextFieldTotalPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButtonRent.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRent.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButtonRent.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRent.setText("RENT CAR");
        jButtonRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRentActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("₺/day");

        javax.swing.GroupLayout jPanelExtrasLayout = new javax.swing.GroupLayout(jPanelExtras);
        jPanelExtras.setLayout(jPanelExtrasLayout);
        jPanelExtrasLayout.setHorizontalGroup(
            jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addComponent(jLabeScooter)
                        .addContainerGap())
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelExtras)
                            .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelHGS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSnowTire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addComponent(jLabelChildSeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelProtection)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExtrasLayout.createSequentialGroup()
                                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxSnowTire, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBoxHGS, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBoxNavigation)
                                            .addComponent(jCheckBoxChildSeat)))
                                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxScooter)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonRent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelHeadlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelTire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelComprehensive, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxHeadlight, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBoxComprehensive, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBoxWindow)
                                            .addComponent(jCheckBoxTire)))
                                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                        .addComponent(jLabelTotalPrice)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldTotalPrice)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)))
                                .addGap(46, 46, 46))))))
        );
        jPanelExtrasLayout.setVerticalGroup(
            jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExtras)
                    .addComponent(jLabelProtection))
                .addGap(18, 18, 18)
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabelChildSeat))
                            .addComponent(jCheckBoxChildSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabelNavigation))
                            .addComponent(jCheckBoxNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxSnowTire, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabelSnowTire)))
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExtrasLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxHGS, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelHGS))))
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTire, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelTire)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabelWindow))
                            .addComponent(jCheckBoxWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxHeadlight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExtrasLayout.createSequentialGroup()
                                .addComponent(jLabelHeadlight)
                                .addGap(14, 14, 14)))
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxComprehensive, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelExtrasLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelComprehensive)))))
                .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabeScooter))
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelTotalPrice))
                    .addGroup(jPanelExtrasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBoxScooter, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addComponent(jButtonRent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonUpdate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonUpdate.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("UPDATE");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImportant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanelExtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelRentCar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonRentCar)
                                .addGap(29, 29, 29)
                                .addComponent(jButtonCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCustomers)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonCars)))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelImportant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCars)
                    .addComponent(jButtonCustomers)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonRentCar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelRentCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelExtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxChildSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxChildSeatActionPerformed
        double price = Double.parseDouble(jTextFieldTotalPrice.getText());
        if(!jCheckBoxChildSeat.isSelected()){
            price -= 30;
        }
        if(jCheckBoxComprehensive.isSelected()){
            price -= 50;
        }
        if(jCheckBoxHGS.isSelected()){
            price -= 60;
        }
        if(jCheckBoxHeadlight.isSelected()){
            price -= 15;
        }
        if(jCheckBoxNavigation.isSelected()){
            price -= 20;
        }
        if(jCheckBoxScooter.isSelected()){
            price -= 15;
        }
        if(jCheckBoxSnowTire.isSelected()){
            price -= 50;
        }
        if(jCheckBoxTire.isSelected()){
            price -= 20;
        }
        if(jCheckBoxWindow.isSelected()){
            price -= 25;
        }
        jTextFieldTotalPrice.setText(String.valueOf((SystemClass.rentedCar.get(0).additionalPrice(price, jCheckBoxChildSeat.isSelected(), jCheckBoxNavigation.isSelected(), jCheckBoxSnowTire.isSelected(), jCheckBoxHGS.isSelected(), jCheckBoxScooter.isSelected(), jCheckBoxTire.isSelected(), jCheckBoxWindow.isSelected(), jCheckBoxHeadlight.isSelected(), jCheckBoxComprehensive.isSelected()))));
    }//GEN-LAST:event_jCheckBoxChildSeatActionPerformed

    private void jCheckBoxNavigationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNavigationActionPerformed
        double price = Double.parseDouble(jTextFieldTotalPrice.getText());
        if(jCheckBoxChildSeat.isSelected()){
            price -= 30;
        }
        if(jCheckBoxComprehensive.isSelected()){
            price -= 50;
        }
        if(jCheckBoxHGS.isSelected()){
            price -= 60;
        }
        if(jCheckBoxHeadlight.isSelected()){
            price -= 15;
        }
        if(!jCheckBoxNavigation.isSelected()){
            price -= 20;
        }
        if(jCheckBoxScooter.isSelected()){
            price -= 15;
        }
        if(jCheckBoxSnowTire.isSelected()){
            price -= 50;
        }
        if(jCheckBoxTire.isSelected()){
            price -= 20;
        }
        if(jCheckBoxWindow.isSelected()){
            price -= 25;
        }
        jTextFieldTotalPrice.setText(String.valueOf((SystemClass.rentedCar.get(0).additionalPrice(price, jCheckBoxChildSeat.isSelected(), jCheckBoxNavigation.isSelected(), jCheckBoxSnowTire.isSelected(), jCheckBoxHGS.isSelected(), jCheckBoxScooter.isSelected(), jCheckBoxTire.isSelected(), jCheckBoxWindow.isSelected(), jCheckBoxHeadlight.isSelected(), jCheckBoxComprehensive.isSelected()))));  
    }//GEN-LAST:event_jCheckBoxNavigationActionPerformed

    private void jCheckBoxHGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHGSActionPerformed
        double price = Double.parseDouble(jTextFieldTotalPrice.getText());
        if(jCheckBoxChildSeat.isSelected()){
            price -= 30;
        }
        if(jCheckBoxComprehensive.isSelected()){
            price -= 50;
        }
        if(!jCheckBoxHGS.isSelected()){
            price -= 60;
        }
        if(jCheckBoxHeadlight.isSelected()){
            price -= 15;
        }
        if(jCheckBoxNavigation.isSelected()){
            price -= 20;
        }
        if(jCheckBoxScooter.isSelected()){
            price -= 15;
        }
        if(jCheckBoxSnowTire.isSelected()){
            price -= 50;
        }
        if(jCheckBoxTire.isSelected()){
            price -= 20;
        }
        if(jCheckBoxWindow.isSelected()){
            price -= 25;
        }
        jTextFieldTotalPrice.setText(String.valueOf((SystemClass.rentedCar.get(0).additionalPrice(price, jCheckBoxChildSeat.isSelected(), jCheckBoxNavigation.isSelected(), jCheckBoxSnowTire.isSelected(), jCheckBoxHGS.isSelected(), jCheckBoxScooter.isSelected(), jCheckBoxTire.isSelected(), jCheckBoxWindow.isSelected(), jCheckBoxHeadlight.isSelected(), jCheckBoxComprehensive.isSelected()))));  
    }//GEN-LAST:event_jCheckBoxHGSActionPerformed

    private void jCheckBoxSnowTireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSnowTireActionPerformed
        double price = Double.parseDouble(jTextFieldTotalPrice.getText());
        if(jCheckBoxChildSeat.isSelected()){
            price -= 30;
        }
        if(jCheckBoxComprehensive.isSelected()){
            price -= 50;
        }
        if(jCheckBoxHGS.isSelected()){
            price -= 60;
        }
        if(jCheckBoxHeadlight.isSelected()){
            price -= 15;
        }
        if(jCheckBoxNavigation.isSelected()){
            price -= 20;
        }
        if(jCheckBoxScooter.isSelected()){
            price -= 15;
        }
        if(!jCheckBoxSnowTire.isSelected()){
            price -= 50;
        }
        if(jCheckBoxTire.isSelected()){
            price -= 20;
        }
        if(jCheckBoxWindow.isSelected()){
            price -= 25;
        }
        jTextFieldTotalPrice.setText(String.valueOf((SystemClass.rentedCar.get(0).additionalPrice(price, jCheckBoxChildSeat.isSelected(), jCheckBoxNavigation.isSelected(), jCheckBoxSnowTire.isSelected(), jCheckBoxHGS.isSelected(), jCheckBoxScooter.isSelected(), jCheckBoxTire.isSelected(), jCheckBoxWindow.isSelected(), jCheckBoxHeadlight.isSelected(), jCheckBoxComprehensive.isSelected()))));  
    }//GEN-LAST:event_jCheckBoxSnowTireActionPerformed

    private void jCheckBoxScooterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxScooterActionPerformed
        double price = Double.parseDouble(jTextFieldTotalPrice.getText());
        if(jCheckBoxChildSeat.isSelected()){
            price -= 30;
        }
        if(jCheckBoxComprehensive.isSelected()){
            price -= 50;
        }
        if(jCheckBoxHGS.isSelected()){
            price -= 60;
        }
        if(jCheckBoxHeadlight.isSelected()){
            price -= 15;
        }
        if(jCheckBoxNavigation.isSelected()){
            price -= 20;
        }
        if(!jCheckBoxScooter.isSelected()){
            price -= 15;
        }
        if(jCheckBoxSnowTire.isSelected()){
            price -= 50;
        }
        if(jCheckBoxTire.isSelected()){
            price -= 20;
        }
        if(jCheckBoxWindow.isSelected()){
            price -= 25;
        }
        jTextFieldTotalPrice.setText(String.valueOf((SystemClass.rentedCar.get(0).additionalPrice(price, jCheckBoxChildSeat.isSelected(), jCheckBoxNavigation.isSelected(), jCheckBoxSnowTire.isSelected(), jCheckBoxHGS.isSelected(), jCheckBoxScooter.isSelected(), jCheckBoxTire.isSelected(), jCheckBoxWindow.isSelected(), jCheckBoxHeadlight.isSelected(), jCheckBoxComprehensive.isSelected()))));  
    }//GEN-LAST:event_jCheckBoxScooterActionPerformed

    private void jCheckBoxTireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTireActionPerformed
        double price = Double.parseDouble(jTextFieldTotalPrice.getText());
        if(jCheckBoxChildSeat.isSelected()){
            price -= 30;
        }
        if(jCheckBoxComprehensive.isSelected()){
            price -= 50;
        }
        if(jCheckBoxHGS.isSelected()){
            price -= 60;
        }
        if(jCheckBoxHeadlight.isSelected()){
            price -= 15;
        }
        if(jCheckBoxNavigation.isSelected()){
            price -= 20;
        }
        if(jCheckBoxScooter.isSelected()){
            price -= 15;
        }
        if(jCheckBoxSnowTire.isSelected()){
            price -= 50;
        }
        if(!jCheckBoxTire.isSelected()){
            price -= 20;
        }
        if(jCheckBoxWindow.isSelected()){
            price -= 25;
        }
        jTextFieldTotalPrice.setText(String.valueOf((SystemClass.rentedCar.get(0).additionalPrice(price, jCheckBoxChildSeat.isSelected(), jCheckBoxNavigation.isSelected(), jCheckBoxSnowTire.isSelected(), jCheckBoxHGS.isSelected(), jCheckBoxScooter.isSelected(), jCheckBoxTire.isSelected(), jCheckBoxWindow.isSelected(), jCheckBoxHeadlight.isSelected(), jCheckBoxComprehensive.isSelected()))));  
    }//GEN-LAST:event_jCheckBoxTireActionPerformed

    private void jCheckBoxWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWindowActionPerformed
        double price = Double.parseDouble(jTextFieldTotalPrice.getText());
        if(jCheckBoxChildSeat.isSelected()){
            price -= 30;
        }
        if(jCheckBoxComprehensive.isSelected()){
            price -= 50;
        }
        if(jCheckBoxHGS.isSelected()){
            price -= 60;
        }
        if(jCheckBoxHeadlight.isSelected()){
            price -= 15;
        }
        if(jCheckBoxNavigation.isSelected()){
            price -= 20;
        }
        if(jCheckBoxScooter.isSelected()){
            price -= 15;
        }
        if(jCheckBoxSnowTire.isSelected()){
            price -= 50;
        }
        if(jCheckBoxTire.isSelected()){
            price -= 20;
        }
        if(!jCheckBoxWindow.isSelected()){
            price -= 25;
        }
        jTextFieldTotalPrice.setText(String.valueOf((SystemClass.rentedCar.get(0).additionalPrice(price, jCheckBoxChildSeat.isSelected(), jCheckBoxNavigation.isSelected(), jCheckBoxSnowTire.isSelected(), jCheckBoxHGS.isSelected(), jCheckBoxScooter.isSelected(), jCheckBoxTire.isSelected(), jCheckBoxWindow.isSelected(), jCheckBoxHeadlight.isSelected(), jCheckBoxComprehensive.isSelected()))));  
    }//GEN-LAST:event_jCheckBoxWindowActionPerformed

    private void jCheckBoxComprehensiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxComprehensiveActionPerformed
        double price = Double.parseDouble(jTextFieldTotalPrice.getText());
        if(jCheckBoxChildSeat.isSelected()){
            price -= 30;
        }
        if(!jCheckBoxComprehensive.isSelected()){
            price -= 50;
        }
        if(jCheckBoxHGS.isSelected()){
            price -= 60;
        }
        if(jCheckBoxHeadlight.isSelected()){
            price -= 15;
        }
        if(jCheckBoxNavigation.isSelected()){
            price -= 20;
        }
        if(jCheckBoxScooter.isSelected()){
            price -= 15;
        }
        if(jCheckBoxSnowTire.isSelected()){
            price -= 50;
        }
        if(jCheckBoxTire.isSelected()){
            price -= 20;
        }
        if(jCheckBoxWindow.isSelected()){
            price -= 25;
        }
        jTextFieldTotalPrice.setText(String.valueOf((SystemClass.rentedCar.get(0).additionalPrice(price, jCheckBoxChildSeat.isSelected(), jCheckBoxNavigation.isSelected(), jCheckBoxSnowTire.isSelected(), jCheckBoxHGS.isSelected(), jCheckBoxScooter.isSelected(), jCheckBoxTire.isSelected(), jCheckBoxWindow.isSelected(), jCheckBoxHeadlight.isSelected(), jCheckBoxComprehensive.isSelected()))));  
    }//GEN-LAST:event_jCheckBoxComprehensiveActionPerformed

    private void jCheckBoxHeadlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHeadlightActionPerformed
        double price = Double.parseDouble(jTextFieldTotalPrice.getText());
        if(jCheckBoxChildSeat.isSelected()){
            price -= 30;
        }
        if(jCheckBoxComprehensive.isSelected()){
            price -= 50;
        }
        if(jCheckBoxHGS.isSelected()){
            price -= 60;
        }
        if(!jCheckBoxHeadlight.isSelected()){
            price -= 15;
        }
        if(jCheckBoxNavigation.isSelected()){
            price -= 20;
        }
        if(jCheckBoxScooter.isSelected()){
            price -= 15;
        }
        if(jCheckBoxSnowTire.isSelected()){
            price -= 50;
        }
        if(jCheckBoxTire.isSelected()){
            price -= 20;
        }
        if(jCheckBoxWindow.isSelected()){
            price -= 25;
        }
        jTextFieldTotalPrice.setText(String.valueOf((SystemClass.rentedCar.get(0).additionalPrice(price, jCheckBoxChildSeat.isSelected(), jCheckBoxNavigation.isSelected(), jCheckBoxSnowTire.isSelected(), jCheckBoxHGS.isSelected(), jCheckBoxScooter.isSelected(), jCheckBoxTire.isSelected(), jCheckBoxWindow.isSelected(), jCheckBoxHeadlight.isSelected(), jCheckBoxComprehensive.isSelected()))));  
    }//GEN-LAST:event_jCheckBoxHeadlightActionPerformed

    private void jButtonRentCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRentCarActionPerformed
        RentingInformation RentingInformation = new RentingInformation();
        RentingInformation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRentCarActionPerformed

    private void jButtonCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomersActionPerformed
        DisplayCustomer displayCustomer = new DisplayCustomer();
        displayCustomer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCustomersActionPerformed

    private void jButtonCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarsActionPerformed
        DisplayCar displayCar = new DisplayCar();
        displayCar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCarsActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        Cancel cancel = new Cancel();
        cancel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        jTextAreaInformation.setText(SystemClass.rentedCar.get(0).toString() + SystemClass.rentedCustomer.get(0).toString());
        
        double discountedPrice = SystemClass.rentedCar.get(0).discountedPrice();
        
        jTextFieldTotalPrice.setText(String.valueOf(Math.round(discountedPrice)));

        //jTextFieldTotalPrice.setText(String.valueOf(formattedPrice.format(discountedPrice)));
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRentActionPerformed
        double totalPrice = Double.parseDouble(jTextFieldTotalPrice.getText());
        
        for (Person customer : SystemClass.customers) {
            if(SystemClass.rentedCustomer.get(0).equals(customer)){
                customer.rentedCars.get(0).setPriceNew(totalPrice);
            }
        }
        
        SystemClass.rentedCar.clear();
        SystemClass.rentedCustomer.clear();
        

        
        RentingInformation RentingInformation = new RentingInformation();
        RentingInformation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentingExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentingExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentingExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentingExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentingExtras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCars;
    private javax.swing.JButton jButtonCustomers;
    private javax.swing.JButton jButtonRent;
    private javax.swing.JButton jButtonRentCar;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JCheckBox jCheckBoxChildSeat;
    private javax.swing.JCheckBox jCheckBoxComprehensive;
    private javax.swing.JCheckBox jCheckBoxHGS;
    private javax.swing.JCheckBox jCheckBoxHeadlight;
    private javax.swing.JCheckBox jCheckBoxNavigation;
    private javax.swing.JCheckBox jCheckBoxScooter;
    private javax.swing.JCheckBox jCheckBoxSnowTire;
    private javax.swing.JCheckBox jCheckBoxTire;
    private javax.swing.JCheckBox jCheckBoxWindow;
    private javax.swing.JLabel jLabeScooter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelChildSeat;
    private javax.swing.JLabel jLabelComprehensive;
    private javax.swing.JLabel jLabelExtras;
    private javax.swing.JLabel jLabelHGS;
    private javax.swing.JLabel jLabelHeadlight;
    private javax.swing.JLabel jLabelImportant;
    private javax.swing.JLabel jLabelNavigation;
    private javax.swing.JLabel jLabelProtection;
    private javax.swing.JLabel jLabelRentCar;
    private javax.swing.JLabel jLabelSnowTire;
    private javax.swing.JLabel jLabelTire;
    private javax.swing.JLabel jLabelTotalPrice;
    private javax.swing.JLabel jLabelWindow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelExtras;
    private javax.swing.JPanel jPanelImportant;
    private javax.swing.JPanel jPanelInformation;
    private javax.swing.JScrollPane jScrollPaneInformation;
    private javax.swing.JTextArea jTextAreaInformation;
    private javax.swing.JTextField jTextFieldTotalPrice;
    // End of variables declaration//GEN-END:variables
}
